### PR TITLE
Remove not neeted port mapping in docker-compose

### PR DESCRIPTION
**Pull request by gorgobacka**
As far as I understand the code, the default port is 8080. There is no need to set the internal port to something else using the environment variables and it might confuses the user. It's only important under which port the app is available from outside of the docker container.

Sorry, for opening so many pull requests recently. But I hope it helps. :) I'm very excited about this project.

### CODE REVIEW

**Comment by vallezw** [comment]
Alright, I edited it a bit to resolve some issues and just used the expose port now without the environment. I hope that's fine with you

**Comment by austozi** [comment]
EDIT: Sorry, ignore this please. I didn't notice the version bump and now I feel like an idiot. The docker-compose.yml works just fine in version 0.4.

> Alright, I edited it a bit to resolve some issues and just used the expose port now without the environment. I hope that's fine with you

I believe this change introduces a regression which an earlier patch resolved: https://github.com/SheetAble/SheetAble-Documentations/pull/2 

Without specifying the environment variable `CONFIG_PATH=/app/config/`, the SQLite database is saved in the root directory in the container, and not persisted in /app/config. As far as my own tests go, nothing is saved in /app/config unless `CONFIG_PATH` is set to this path.

On the other hand, the volume mapping `/local/path/config/dir:/app/config` is meant to persist the application data, such as the SQLite database. However, this line is currently redundant because it simply creates an empty folder that never gets populated with anything.

For the docker-compose.yml file to work as intended, both the `CONFIG_PATH` environment variable and volume mapping need to be set. The docker-compose.yml file should look like this:

```
version: "3"
services:  
  sheetable:
    container_name: sheetable
    restart: unless-stopped
    image: vallezw/sheetable
    ports:
      - 80:8080
    environment:
      - CONFIG_PATH=/app/config/
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /local/path/config/dir:/app/config
```

**Comment by vallezw** [comment]
Hey no problem. It's great to have contributions. I'll change it in the docs this evening, but thank you for staying with this PR!

**Comment by vallezw** [comment]
> EDIT: Sorry, ignore this please. I didn't notice the version bump and now I feel like an idiot. The docker-compose.yml works just fine in version 0.4.
> 
> > Alright, I edited it a bit to resolve some issues and just used the expose port now without the environment. I hope that's fine with you
> 
> I believe this change introduces a regression which an earlier patch resolved: #2
> 
> Without specifying the environment variable `CONFIG_PATH=/app/config/`, the SQLite database is saved in the root directory in the container, and not persisted in /app/config. As far as my own tests go, nothing is saved in /app/config unless `CONFIG_PATH` is set to this path.
> 
> On the other hand, the volume mapping `/local/path/config/dir:/app/config` is meant to persist the application data, such as the SQLite database. However, this line is currently redundant because it simply creates an empty folder that never gets populated with anything.
> 
> For the docker-compose.yml file to work as intended, both the `CONFIG_PATH` environment variable and volume mapping need to be set. The docker-compose.yml file should look like this:
> 
> ```
> version: "3"
> services:  
>   sheetable:
>     container_name: sheetable
>     restart: unless-stopped
>     image: vallezw/sheetable
>     ports:
>       - 80:8080
>     environment:
>       - CONFIG_PATH=/app/config/
>     volumes:
>       - /etc/localtime:/etc/localtime:ro
>       - /local/path/config/dir:/app/config
> ```

Alright, thanks for testing it. I didn't know it wouldn't work without the env config path configured since it worked in my case however I'll add to the docs in case anyone has got that issue as well.

**Pull request merged**
