### PR TITLE
Update introduction.mdx

### PR DESCRIPTION
**Pull request by g-gaudio**
Cleaned up the introduction a bit, hope it's okay :)

### CODE REVIEW

**Comment by vallezw** [comment]
Hey @g-gaudio, you had a few bugs in there when running it locally. I suggest when making changes here you try it out locally, lmk if you have any problems setting it up. Also I changed a few words, but kept in the same way overall.

Thanks for the PR and lmk if you are fine with the changes and that I can merge them.

**Comment by g-gaudio** [comment]
oh gotcha, I'm still new to github so I'll try to figure out how to fix the bugs. Thanks :)

**Comment by g-gaudio** [comment]
Oh and I'm good with any changes of course!

**Comment by vallezw** [comment]
Alright 👌

**Pull request merged**
